# Backend https://www.netlifycms.org/docs/configuration-options/#backend
backend:
  name: git-gateway
  branch: main

# Publish mode https://www.netlifycms.org/docs/configuration-options/#publish-mode
publish_mode: editorial_workflow

# Media and Public Folders https://www.netlifycms.org/docs/configuration-options/#media-and-public-folders
media_folder: "/static/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/images/uploads"

# Collections https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: Components
    name: components
    files:
      - name: "header"
        label: Header
        format: json
        file: "/content/header.json"
        fields:
          - { label: Title, name: title, widget: string }

  - label: Main Pages
    name: main-pages
    files:
      - name: "index"
        label: Home Page
        format: json
        file: "/content/index.json"
        fields:
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: "Main Image",
              name: mainImage,
              widget: image,
              required: false,
            }

      - name: "about"
        label: About Page
        format: json
        file: "/content/about.json"
        fields:
          - { label: Heading, name: heading, widget: string }
